### ISSUE TITLE
Ajax callbacks will never execute

### ISSUE THREAD

**Issue by khalwat** [BosNaufal/vue2-autocomplete#11]
This callback `onAjaxProgress` will never get called because in the context, `this` refers to the `XMLHttpRequest`:

```
          ajax.addEventListener('progress', function (data) {
            if(data.lengthComputable){
              // Callback Event
              this.onAjaxProgress ? this.onAjaxProgress(data) : null
            }
          });
```

Ditto with the `onAjaxLoaded` callback.

**Comment by khalwat** [comment]
This PR fixes it: https://github.com/BosNaufal/vue2-autocomplete/pull/16

**Comment by BosNaufal** [comment]
Hi @khalwat! :grin: 
Thanks for giving me a pull request. But sorry, i haven't yet checked your PR before I updated the package. Check our new autocomplete~
