### ISSUE TITLE
`process` method missing from dist?

### ISSUE THREAD

**Issue by khalwat** [BosNaufal/vue2-autocomplete#12]
In the source you have the very useful (and needed by me) method `process` which can be used to process the raw JSON received:

```
            self.json = self.process ? self.process(json) : json;
```

https://github.com/BosNaufal/vue2-autocomplete/blob/master/src/js/components/vue-autocomplete.vue#L293

Yet this method, and the call to it above seems to be nowhere to be found in the `dist` version of the code. Did something not get checked in properly, perhaps?

Also the version listed in the github `package.json` is `0.0.3` but the version I'm seeing when I install it is `0.0.4` -- is something perhaps out of sync here?

**Comment by khalwat** [comment]
This PR fixes it: https://github.com/BosNaufal/vue2-autocomplete/pull/16

**Comment by madr** [comment]
I noticed it was missing too, si I at least added it to my PR on a other topic: #17

Is it something else that is missing from the README?

**Comment by BosNaufal** [comment]
Hi guys! @khalwat @madr 
Thanks for giving me an issue~
That's all my bad~ but now you can use the proccess method from the package...~
