### ISSUE TITLE
Make parameter format configurable?

### ISSUE THREAD

**Issue by Steve-MP** [BosNaufal/vue2-autocomplete#18]
As this component assumes that the source API will always request a url parameter in the format "?p=myvalue" it does not seem to be usable with APIs that use more readable API endpoints - e.g. "/suggestions/myvalue".

Could it be possible to make this configurable so that it does not force an x=y format and is compatible with such APIs?

**Comment by BosNaufal** [comment]
Hi @Steve-MP, 
Thanks for giving me an issue. Now you can use manual ajax process by using the ```onShouldGetData``` props.
