### ISSUE TITLE
Option to disable escaping

### ISSUE THREAD

**Issue by errogaht** [BosNaufal/vue2-autocomplete#19]
I want show hightligted results.
In this case backend send html.
But you auto escape html and it not work as i want.
How i can show html in anchor and label ?

**Comment by BosNaufal** [comment]
Hi @errogaht 
Thanks for giving me an issue. Now you can shape the child as you want. Check it out~
https://github.com/BosNaufal/vue2-autocomplete#onshouldrenderchild-function
Commit > https://github.com/BosNaufal/vue2-autocomplete/commit/de5f87d11969acf118893cbee043767b9a8d1a0b
