### ISSUE TITLE
TypeError: t._v is not a function

### ISSUE THREAD

**Issue by mailnike** [BosNaufal/vue2-autocomplete#2]
Any idea why I am getting this error:

TypeError: t._v is not a function
    at Proxy.render (eval at <anonymous> 

---

I added below code in my blade.php template:

```
<autocomplete1
                                                                url="/api/list"
                                                                anchor="name"
                                                                >
                                                        </autocomplete1>
```

and in the .js file:

```
import Autocomplete1 from 'vue2-autocomplete-js';
Vue.component('abc-api', {
    components: { Autocomplete1 },
```

**Comment by BosNaufal** [comment]
Hey @mailnike,
Thanks for giving me an issue, but I think it can be caused by your url location. You need to put complete url i.e. "http://yourwebsite.com/the/apis :grin: :+1:

**Comment by mailnike** [comment]
Thanks @BosNaufal but no luck. Tried again with full URL and also removed middleware authentication to see if that was the problem.

**Comment by BosNaufal** [comment]
@mailnike Would you like to reproduce it via http://jsonplaceholder.typicode.com/ and webpackbin or codepen or jsfiddle or somthing else? so, I can check the problem.

**Comment by mailnike** [comment]
@BosNaufal I found the issue. If I comment the auth middleware then it works. Is there anyway I can pass XSRF token? or do I need to pass it? 

If I do API call in VUEJS then LARAVEL Spark takes care of this in the backend but for AJAX call I am passing it explicitly.

**Comment by BosNaufal** [comment]
Hey @mailnike, Just simply remove the auth in your search route. Or you can make it (the search route) to read the token via url query. I think it's just the BackEnd problem.
