### ISSUE TITLE
Params instead of Param in Readme.md

### ISSUE THREAD

**Issue by michalsindelar** [BosNaufal/vue2-autocomplete#22]
In `Readme.md` file is typo.

> param**S** (String)
> name of the search parameter to query in Ajax call. default is q=

According to code should be only `param`.

```
// query param
param: {
   type: String,
   default: 'q'
},
```
`vue-autocomplete.vue`

**Comment by atutweb** [comment]
Tanks @michalsindelar 
I use from param and send custom request 
<autocomplete
    url="http://x.com/api/industry/"
    anchor="name"
    param ="filter"
    :on-select="getData">
  </autocomplete>

**Comment by BosNaufal** [comment]
Hi All~ @michalsindelar @atutweb 
It's just fixed~ thanks! https://github.com/BosNaufal/vue2-autocomplete/commit/d3159f824b8be0909b1de85a9c125eaaa1ba8b46
