### ISSUE TITLE
Get Input Value :on-blur="onBlur"

### ISSUE THREAD

**Issue by bobbygerez** [BosNaufal/vue2-autocomplete#29]
How can I get the value onBlur events. Thanks

```
onBlur(q){
          console.log(q);
          
        },
```

**Comment by BosNaufal** [comment]
Hi @bobbygerez 
Thanks for giving me an issue~ You can use ```$refs``` https://github.com/BosNaufal/vue2-autocomplete/commit/d3159f824b8be0909b1de85a9c125eaaa1ba8b46

```javascript
const value = this.$refs.autocomplete.type
console.log(value)
```
