### ISSUE TITLE
In vue-autocomplete.vue  file, "this"   is used in error way .

### ISSUE THREAD

**Issue by herrdu** [BosNaufal/vue2-autocomplete#31]
the error code: 

 ajax.addEventListener('loadend', function (data) {
            let json = JSON.parse(this.responseText);

            // Callback Event
            this.onAjaxLoaded ? this.onAjaxLoaded(json) : null

            self.json = self.process ? self.process(json) : json;
          });

"this.onAjaxLoaded "  should be modifd to "self.onAjaxLoaded "

**Comment by BosNaufal** [comment]
Hi @herrdu,
That's all my bad. But now, you can check the latest version of it~
