### ISSUE TITLE
When selected one item from autocomplete , textfield empty 

### ISSUE THREAD

**Issue by atutweb** [BosNaufal/vue2-autocomplete#32]
When selected one item from autocomplete i call function  then i will that empty textfield autocomplete . how to?

<autocomplete
    url="http://x.com/api/industry/"
    anchor="name"
    param ="filter"
    :on-select="getData"
  >

 methods: {
      getData(obj){
        app2.list_locations.push(obj.name);
        // i will empty autocomplete 
...
      }

**Comment by BosNaufal** [comment]
Hi @atutweb,
When you in callback ```onSelect``` you can set the value using autocomplete methods
```
this.$refs.autocomplete.setValue("halo")
```
It's mentioned in the docs as well
https://github.com/BosNaufal/vue2-autocomplete#setvalue-string
