### ISSUE TITLE
Can not specific model

### ISSUE THREAD

**Issue by lettucebo** [BosNaufal/vue2-autocomplete#33]
I'm using autocomplete 

find out model name always be "**_type_**"

can't change to another model

**Comment by BosNaufal** [comment]
Hi @lettucebo,
Thanks for giving me an issue. But I'm sorry, I can't get your point. Would you like to tell me what are you trying to do with the model or with the value?

**Comment by Konafets** [comment]
I guess @lettucebo wants the same behavior as it is for a normal input field, where you add `v-model` and the input shows the value of the model. With autocomplete this does not work. I guess `:initialValue` should be used instead.

Unfortunately this does not work either. See #46.
