### ISSUE TITLE
Setting attributes for input

### ISSUE THREAD

**Issue by JCWolf** [BosNaufal/vue2-autocomplete#37]
Hi there,

Is there a way to set attributes for the input element? I want to set the name attribute. I don't see any reference to this in the documentation.

Thank you, great work.

**Comment by BosNaufal** [comment]
Hi @JCWolf 
I think, I forgot to write about that in the documentation
Here it is: https://github.com/BosNaufal/vue2-autocomplete/blob/master/src/js/components/vue-autocomplete.vue#L9

If you need any other feature, just let me know~
