### ISSUE TITLE
Add possiblity to make field mandatory

### ISSUE THREAD

**Issue by Konafets** [BosNaufal/vue2-autocomplete#40]
The component should take a prop `required` which is passed to the input field. If it set to `true` the field is using HTML5 browser validation.

**Comment by BosNaufal** [comment]
Hi @Konafets, It's another good idea. :grin: :+1:

**Comment by BosNaufal** [comment]
Hi @Konafets,
Thanks for giving me an issue and another good idea to enhance the component.
Please check the latest change here https://github.com/BosNaufal/vue2-autocomplete/commit/5077c1d8c9470a3df27d063538392bdbf9a570fe
