### ISSUE TITLE
Initial value can not set

### ISSUE THREAD

**Issue by Konafets** [BosNaufal/vue2-autocomplete#46]
In an edit form I want to show the already stored value inside an input field managed by autocomplete. If I understand the documentation correct the prop `:initValue` should used to set a initial value of the input. 

However this does not work. The input field remains empty.

**Comment by Konafets** [comment]
`:init-value` did the trick on `inline-templates`.

**Comment by deminua** [comment]
Tell me please how you solved the problem? If you can tell more in detail ...

**Comment by chandug4u** [comment]
This is how I was able to set the initial value..

in Html

```
<autocomplete 
     ref="autocomplete"
  </autocomplete>
```

in vuejs

```
new Vue({
    el: '#app',
    mounted: function () {
        this.$refs.autocomplete.setValue('Hello');
}
});

```

or else you can use  this.$refs.autocomplete.setValue() method in click events like for example if you want to set the value when clicked on a button, etc
