### ISSUE TITLE
Debounce not working

### ISSUE THREAD

**Issue by KimPrince** [BosNaufal/vue2-autocomplete#55]
I set debounce to 2000 using  `:debouce=2000` and min 3 using `:min=3`.

When I quickly type 123456789, the component issues 7 requests, with query parameters of:

```
?q=123
?q=1234
?q=12345
?q=123456
?q=1234567
?q=12345678
?q=123456789
```

Note that the requests are not necessarily sent in that order.

**Comment by tarreislam** [comment]
same here

**Comment by philippeapril** [comment]
Did you make a typo: "debouce" instead of "debounce"? debounce (in the docs) worked for me and I tried with 2000 and min 3 and it only sent 1 request at the end.

If that's not it, maybe it's related to the browser you're using..?

**Comment by tarreislam** [comment]
..... I apperently wrote `debunce` and OP wrote `debouce`

Thank you for the spelling lecture Philip.
