### ISSUE TITLE
Scrolling Problem

### ISSUE THREAD

**Issue by molerat619** [BosNaufal/vue2-autocomplete#67]
If our autocomplete results are too many, the list is as long as it needs to be without having a maximum size. We want to limit the size to have the user scroll within the results-window, because the parent element is not big enough.

What's the best way to achieve that?

**Comment by constantm** [comment]
@molerat619 Can't this be done by simply setting `max-height` and `overflow-y: auto;` on the search results?

**Comment by molerat619** [comment]
Yes, we fixed it now. But we couldn't imagine we were the only ones who need this and thought there was an implemented solution already so we don't have to add our own css for this.

**Comment by peacefulseeker** [comment]
Yes, and then comes another problem when navigating with arrows(down + up). It does not scroll to selected element by default. 
Will make a pull request later to fix that.
