### ISSUE TITLE
Unset/clear input v-model

### ISSUE THREAD

**Issue by mikicoding** [BosNaufal/vue2-autocomplete#71]
Hello,
In my case i fetch the data via ":onInput" instead of "url" and I need to unset/clear the input. Using v-model in component is been ignored. Any idea how to do this?

There has been a similar case with https://github.com/paliari/v-autocomplete/issues/34 beeing solved.

thanks!

**Comment by HumbertoMendes** [comment]
Hi,

I could achieve that following the example @constantm gave on issue #65:

Adding a ref to autocomplete component:

```
<autocomplete
      ref="autocomplete"
      :url="..."
      anchor="..."
      :onInput="callbackEvent">
</autocomplete>
<div class="remove-item" @click="removeItem"></div>
```

And then setting the value through:

```
export default {
  components: {
    autocomplete: Vue2Autocomplete
  },
  removeItem: function() {
    this.$refs.autocomplete.setValue('')
  }
}
```

Worked for me, please see if this will work for you too.

**Comment by mikicoding** [comment]
Nice, it works. Thank you!
