### ISSUE TITLE
Is it possible to add parameters in the url ? 

### ISSUE THREAD

**Issue by FlorianChretien** [BosNaufal/vue2-autocomplete#74]
Hello,

Here is my configuration:

`url="http://localhost/truc/truc/action/data_truc.php"`
`param="action=listUti&q"`

I try to add my configuration but it does not filter the results, however it scopes my search ($ event.target.value).

A solution ? Thank you very much.

**Comment by BosNaufal** [comment]
Hi @FlorianChretien,
Sure, It's very possible. You can pass it via `customParams` props. check out the documentation:
```html
<autocomplete
  ...
  :customParams="{ token: 'dev' }"
/>
```
