### ISSUE TITLE
What is the best way to set a listener for input?

### ISSUE THREAD

**Issue by amorphine** [BosNaufal/vue2-autocomplete#77]
I'd like the Enter key pressing call a function at root. 
Usually we use `@keyup.enter` but the component is 3rd party so we cannot change the source without forking. 
What should I do? What are the best practices?

**Comment by BosNaufal** [comment]
Hi @amorphine,
Sure you can do it. using old way `addEventListener` to the input. You can get the input using reference. You can try this
```javascript
const input = this.$refs.autocomplete.$refs.input
document.addEventListener(input, this.someRootMethod, false) 
```
