### ISSUE TITLE
how can i inject html after input

### ISSUE THREAD

**Issue by mohammad6006** [BosNaufal/vue2-autocomplete#81]
I need to add this html code after input tag

```
   <span class="fa fa-globe form-control-feedback"></span>    
````

what can I do?

**Comment by BosNaufal** [comment]
Hey @mohammad6006,
Would you like to elaborate more on what are you trying to do? cause I can't get your point...

Maybe you need to check this out
[onShouldRenderChild](https://github.com/BosNaufal/vue2-autocomplete#setvalue-string)

```html
<autocomplete
  anchor="formatted_address"
  label="formatted_address"
  :onShouldRenderChild="renderChild"
>
</autocomplete>
```
```javascript
methods: {
  renderChild(data) {
    return `
      <img src="${data.src}" />
      <span>${data.something}</span>
    `
  },
}
```

**Comment by mohammad6006** [comment]
But onShouldRenderChild could change custom template for the list But I need custom template for div form-group

as you see in this image  
![image](https://user-images.githubusercontent.com/553379/43573740-b55c2cda-9657-11e8-9916-2d1f3b2e7cbf.png)

It rendered in ul list but I need inject it after input tag in div form group

its main html code without autocomplete : 
```
                    <div class="form-group has-success has-feedback">
                        <input type="text" class="form-control" id="inputSuccess" placeholder="کافه رستورانو...">
                        <span class="fa fa-plus form-control-feedback"></span>
                    </div>
```

I couldn't find any method to render span tag after input tag in div form-group
