### ISSUE TITLE
Input cleared after selecting element in list

### ISSUE THREAD

**Issue by ilyachase** [BosNaufal/vue2-autocomplete#86]
Hi. I'm new with Vue and I'm wondering why the input value clears out after `:on-select` event. And what is a proper way to keep it. Also neither :value or v-model not working with this element.

`this.$refs.input.value = "test21231";` also does not work.

Sorry for simple question.

My example:

```html
<autocomplete
    url="https://geocode-maps.yandex.ru/1.x/"
    anchor="GeoObject.name"
    label="GeoObject.description"
    param="geocode"
    id="address_input"
    :custom-params="{ format: 'json' }"
    :process="processJSON"
    :classes="{ input: 'form-control'}"
    :on-select="fillAddressData"
    :debounce="500">
</autocomplete>
```

```javascript
var vm = new Vue( {
    el: '#events-form',
    data: {
        processJSON: function ( json ) {
            return json.response.GeoObjectCollection.featureMember;
        },
        fillAddressData: function ( json ) {
            json.GeoObject.metaDataProperty.GeocoderMetaData.Address.Components.forEach( function ( el ) {
                if ( el.kind === "locality" ) {
                    vm.city_text = el.name;
                }
            } );

            vm.coord1 = json.GeoObject.Point.pos.split( " " )[ 0 ];
            vm.coord2 = json.GeoObject.Point.pos.split( " " )[ 1 ];
        },
        city_text: "",
        coord1: "",
        coord2: "",
        address_text: ""
    },
    components: {
        autocomplete: Vue2Autocomplete.default
    }
} );
```

**Comment by BosNaufal** [comment]
Hey @ilyachase 

**To keep the value after select the list item**
have you check the example [here](https://rawgit.com/BosNaufal/vue2-autocomplete/master/index.html)?

**And to set value in the autocomplete**
You can use [this method](https://github.com/BosNaufal/vue2-autocomplete#setvalue-string). Example:
```javascript
this.$refs.autocomplete.setValue("test21231")
```

**Comment by ilyachase** [comment]
> To keep the value after select the list item

In the example some data from json answer is inserted every time I select item.

> this.$refs.autocomplete.setValue("test21231")

I tried - This just didn't worked for me.
