### ISSUE TITLE
Support to make it work with an options array

### ISSUE THREAD

**Issue by mimani** [BosNaufal/vue2-autocomplete#9]
Hi, 

Thanks for this awesome plugin.

Currently it expects an `url` for search. in My use-case, I have the options in an array in my vue application itself. Can there be support added for accepting an array in input and than suggest from that array.

Thanks.

**Comment by jjjachyty** [comment]
my request need set headers ，the post／get request  have  a headers options set？

**Comment by kevcodez** [comment]
+1 for @jjjachyty - how would I set headers?

**Comment by BosNaufal** [comment]
Hi All!
Thanks for giving me an issue~

The ```options``` props is for you @mimani and....
the ```onShouldGetData``` props is made for your need @jjjachyty & @kevcodez 

Thanks! :grin: :+1:
